### ISSUE TITLE
Multiple keypad.

### ISSUE THREAD

**Issue by fredericplante** [arduino12/ttp229b-arduino#1]
This is not really an issue, I was wondering if there were ways to scan 4 keypads, using your library?

**Comment by arduino12** [comment]
Each keypad needs clk_pin and data_pin, so for the price of 8 gpio pins you can,
But I think you can connect all clk_pins together to the same arduino pin- for a total of 5 pins for 4 keypads.

**Comment by fredericplante** [comment]
In any ways, it would require 4cs pin + clk and data, if I put some chip select on the 4  them, using a 74**00, for exemple,

**Comment by fredericplante** [comment]
Yeap, that would work.
