### ISSUE TITLE
HOW TO INSTALL LIBRARY

### ISSUE THREAD

**Issue by KINGDOMWARE** [arduino12/ttp229b-arduino#2]
Your library is not installing, because repository has installed library for TTP229 LSF with I2C interface named TTP229

Your library is for TTP229-BSF chip. It is not the same! It doesnt have I2C

Make a new CORRECT library and name it TTP229B

**Comment by arduino12** [comment]
Done!
Thanks for noticing!

**Comment by KINGDOMWARE** [comment]
If you woudnt mind, i will make some new useful functions instead. Keep en eye
